// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cklxxtqgcsvnxweozdai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbHh4dHFnY3N2bnh3ZW96ZGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODk5NDcsImV4cCI6MjA2ODg2NTk0N30.fBy2hztZusNSx_51rT2HsOTAt2IOAAT5j5PJGlf_vm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});